# This file is a template, and might need editing before it works on your project.
# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex
image: listx/texlive:2017

stages:
 - build
 - test

pdflatex_builder:
  stage: build
  before_script:
    - cd latex
  script:
    - "latexmk -pdf -output-directory=pdflatex/ thesis.tex"
  artifacts:
    paths:
      - "latex/pdflatex/thesis.pdf"

xelatex_builder:
  stage: build
  before_script:
    - cd latex
  script:
    - "latexmk -xelatex -output-directory=xelatex/ thesis.tex"
  artifacts:
    paths:
      - "latex/xelatex/thesis.pdf"

pdflatex_content_validator:
  stage: test
  script:
    - "pdfinfo latex/pdflatex/thesis.pdf |grep '^Pages: *13$'"

xelatex_content_validator:
  stage: test
  script:
    - "pdfinfo latex/xelatex/thesis.pdf |grep '^Pages: *13$'"
