
# see https://hub.docker.com/repository/docker/konttipoju/tinytex
image: konttipoju/tinytex:2020-06c

# build latex/thesis.tex -> latex/thesis.pdf using pdflatex
# shell-escape functionality is required by the minted package
build:
  stage: build
  script:
    - cd latex
    - latexmk -pdf --shell-escape thesis.tex
  artifacts:
    paths:
      - latex/thesis.pdf

# a validation prints "PASS + something" is the file is PDF/A conformant
validate:
  stage: test
  script:
    - pdfa-validate latex/thesis.pdf|grep '^PASS'
