name: Build LaTeX document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up TeXLive
        uses: dante-ev/latex-action@edge
        with:
          texlive-version: '2021'
      - name: Build LaTeX document
        run: |
          cd latex
          latexmk -pdf --shell-escape thesis.tex
      - name: Validate PDF/A
        run: |
          pdfa-validate latex/thesis.pdf | grep '^PASS'
        continue-on-error: true
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: public
          clean: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}