name: Build LaTeX document

on:
  push:
    branches:
      - main

jobs:
  draft_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up TeXLive
        uses: dante-ev/latex-action@edge
        with:
          texlive-version: '2021'
      - name: Build draft version
        run: |
          cp -r latex draft
          cd draft
          cp thesis.tex thesis2.tex
          sed -i 's/version=final/version=draft/g' *.tex
          latexmk -pdf --shell-escape thesis.tex
          latexmk -xelatex --shell-escape thesis2.tex
          pdfinfo thesis.pdf | grep '^Pages: *16$'
          pdfinfo thesis2.pdf | grep '^Pages: *16$'
      - name: Upload draft version artifacts
        uses: actions/upload-artifact@v2
        with:
          name: draft-version
          path: draft

  final_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up TeXLive
        uses: dante-ev/latex-action@edge
        with:
          texlive-version: '2021'
      - name: Build final version
        run: |
          cd latex
          cp thesis.tex thesis2.tex
          latexmk -pdf --shell-escape thesis.tex
          latexmk -xelatex --shell-escape thesis2.tex
          pdfinfo thesis.pdf | grep '^Pages: *16$'
          pdfinfo thesis2.pdf | grep '^Pages: *16$'
          pdfa-validate thesis.pdf | grep '^PASS'
          pdfa-validate thesis2.pdf | grep '^PASS'
        continue-on-error: true
      - name: Upload final version artifacts
        uses: actions/upload-artifact@v2
        with:
          name: final-version
          path: latex

  testsuite_pdflatex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up TeXLive
        uses: dante-ev/latex-action@edge
        with:
          texlive-version: '2021'
      - name: Download and extract testsuite
        run: |
          wget https://tech.utugit.fi/soft/thesis/testsuite/testsuite.tar.gz
          tar xf testsuite.tar.gz
        working-directory: ${{ github.workspace }}
      - name: Copy .cls files
        run: |
          cp latex/*cls .
        working-directory: ${{ github.workspace }}
      - name: Run pdflatex testsuite
        run: |
          ./bash_unit test_pdflatex.sh
        working-directory: ${{ github.workspace }}

  testsuite_xelatex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up TeXLive
        uses: dante-ev/latex-action@edge
        with:
          texlive-version: '2021'
      - name: Download and extract testsuite
        run: |
          wget https://tech.utugit.fi/soft/thesis/testsuite/testsuite.tar.gz
          tar xf testsuite.tar.gz
        working-directory: ${{ github.workspace }}
      - name: Copy .cls files
        run: |
          cp latex/*cls .
        working-directory: ${{ github.workspace }}
      - name: Run xelatex testsuite
        run: |
          ./bash_unit test_xelatex.sh
        working-directory: ${{ github.workspace }}

  deploy:
    runs-on: ubuntu-latest
    needs: final_version
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Download sitegen.jar
        run: |
          wget https://tech.utugit.fi/soft/tools/sitegen/sitegen.jar -O sitegen.jar
        working-directory: ${{ github.workspace }}
      - name: Generate PDF.js version of thesis
        run: |
          cp latex/thesis.pdf .
          java -jar sitegen.jar -pdfjs
        working-directory: ${{ github.workspace }}
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: public
          clean: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}